export const UPDATE_BLOCKNOTES_BASE = 'UPDATE_BLOCKNOTES_BASE'
export const LOAD_BASE = "LOAD_BASE"
export const LOAD_CARDS = 'LOAD_CARDS'
export const LOADING = "LOADING"

export const LOGOUT = 'LOGOUT'
export const SAGALOGOUT = 'SAGALOGOUT'

export const AUTHENTICATED = 'AUTHENTICATED'
export const SAGAAUTHENTICATED = "SAGAAUTHENTICATED"
export const SAGAREGISTRATION = "SAGAREGISTRATION"

export const UPDATE_USERINFO = "UPDATE_USERINFO"
export const SAGA_UPDATE_USERINFO = 'SAGA_UPDATE_USERINFO'

export const CHANGE_BLOCKNOTESLIST = 'CHANGE_BLOCKNOTESLIST'
export const SAGA_CHANGE_BLOCKNOTELIST = 'SAGA_CHANGE_BLOCKNOTELIST'

export const DELETE_BLOCKNOTE = 'DELETE_BLOCKNOTE'
export const SAGA_DELETE_BLOCKNOTE = 'SAGA_DELETE_BLOCKNOTE'

export const EDIT_BLOCKNOTE = "EDIT_BLOCKNOTE"
export const SAGA_EDIT_BLOCKNOTE = "SAGA_EDIT_BLOCKNOTE"

export const ADD_CARD = "ADD_CARD"
export const SAGA_ADD_CARD = "SAGA_ADD_CARD"

export const UPDATE_BLOCKNOTE_AND_CARDS = "UPDATE_BLOCKNOTE_AND_CARDS"
export const SAGA_DELETE_CARD = "SAGA_DELETE_CARD"
export const SAGA_EDIT_CARD_BODY = "SAGA_EDIT_CARD_BODY"
export const SAGA_EDIT_CARD_HEAD = "SAGA_EDIT_CARD_HEAD"
export const SAGA_ADD_TAG = 'SAGA_ADD_TAG'
export const SAGA_REMOVE_TAG = 'SAGA_REMOVE_TAG'
